# config.yaml

# =======================================================
# 파이프라인 실행 설정
# =======================================================

# 1. 실행 단계 설정
# 실행할 파이프라인의 마지막 단계를 지정합니다.
# 'naver': 네이버 크롤링만 실행 후 종료
# 'kakao': 카카오 크롤링까지 실행 후 종료
# 'full': 점수 산정까지 전체 파이프라인 실행 (기본값)
pipeline_stage: 'full'

# 2. 크롤링 공통 설정
# 네이버 크롤러의 최대 스레드 수는 3개로 제한됩니다.
num_threads: 1
# true: 브라우저 창을 숨기고 백그라운드에서 실행 (서버/자동화 환경용)
# false: 브라우저 창을 화면에 표시 (로컬 테스트/디버깅용)
headless_mode: false

# 3. 네이버 중간 저장 설정
# 스레드가 2개 이상일 때, 몇 개의 가게를 크롤링할 때마다 중간 저장할지 결정합니다.
# 0으로 설정하면 중간 저장 기능을 사용하지 않습니다.
save_interval: 0

# 4. 경로 설정 (도커 컨테이너 내부 경로 기준)
# 이 경로들은 docker run 명령어의 볼륨 매핑을 통해 실제 로컬 경로와 연결됩니다.
data_dir: 'data'
output_dir: 'results'
input_csv_name: 'input_data.csv'

# 5. 최종 결과 저장 형식 설정
# 'csv', 'json', 'both' 중 하나를 선택할 수 있습니다.
# 'both'로 설정 시 CSV와 JSON 파일 두 가지 형태로 모두 저장됩니다.
output_format: 'json'

# 6