# config.yaml (최종 수정본)

# =======================================================
# 파이프라인 실행 설정
# =======================================================

# 1. 실행 단계 설정
# 실행할 파이프라인의 마지막 단계를 지정합니다.
# 'naver': 네이버 크롤링만 실행
# 'kakao': 카카오 크롤링까지 실행
# 'full': 점수 산정까지 전체 파이프라인 실행 (기본값)
pipeline_stage: 'full'


# 2. 크롤링 공통 설정
# 카카오맵 크롤링 시 사용할 최대 스레드 수 입니다.
# (참고: 새로운 네이버 크롤러는 단일 작업당 1개의 스레드만 사용합니다.)
num_threads: 3

# true: 브라우저 창을 숨기고 백그라운드에서 실행 (서버/자동화 환경용)
# false: 브라우저 창을 화면에 표시 (로컬 테스트/디버깅용)
headless_mode: true


# 3. 경로 설정
# 점수 산정 단계에서 필요한 데이터(매핑 파일, 폴리곤 등)가 위치한 디렉토리
data_dir: 'data'
# 모든 결과물이 저장될 최상위 디렉토리
output_dir: 'results'


# 4. 최종 결과 저장 형식
# 'csv', 'json', 'both' 중 하나를 선택할 수 있습니다.
output_format: 'json'
# =======================================================